version: '3.8'
services:
  web:
    image: ${DOCKER_USER}/${REPO_NAME}:${TAG}
    environment:
      MQTT_BROKER_HOST: ${MQTT_BROKER_HOST}
      MQTT_USER_NAME: ${MQTT_USER_NAME}
      MQTT_TOKEN: ${MQTT_TOKEN}
      API_BASE_URL: ${API_BASE_URL}
    restart: always
    build:
      context: ./
    command: /dist
    networks:
      - homethings-rest-api_homethings
networks:
  homethings-rest-api_homethings:
    external: true