name: Docker CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
  deploy:
    runs-on: self-hosted
    needs: test
    env:
      MQTT_BROKER_HOST: ${{ secrets.MQTT_BROKER_HOST }}
      MQTT_USER_NAME: ${{ secrets.MQTT_USER_NAME }}
      ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
      ROLLBAR_ENV: ${{ secrets.ROLLBAR_ENV }}
      MQTT_TOKEN: ${{ secrets.MQTT_TOKEN }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: Run docker image
      run: docker-compose up -d --build -V