name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
        MQTT_BROKER_HOST: ${{ secrets.MQTT_BROKER_HOST }}
        MQTT_USER_NAME: ${{ secrets.MQTT_USER_NAME }}
        ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
        ROLLBAR_ENV: ${{ secrets.ROLLBAR_ENV }}
        MQTT_TOKEN: ${{ secrets.MQTT_TOKEN }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Determine tag based on git commit
        id: set-tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Check if tag is defined
        run: exit 1
        if: env.TAG == ''
      - name: Run docker image
        run: docker-compose up -d --build -V