name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
        MQTT_BROKER_HOST: ${{ secrets.MQTT_BROKER_HOST }}
        MQTT_USER_NAME: ${{ secrets.MQTT_USER_NAME }}
        MQTT_TOKEN: ${{ secrets.MQTT_TOKEN }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determine tag based on git commit
        id: set-tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Check if tag is defined
        run: |
          if [ -z "$TAG" ]; then
            exit 1
          fi
      - name: Run docker image
        run: docker-compose up -d --build -V