name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ secrets.REPO_NAME }}

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
  build:
    runs-on: self-hosted
    needs: test
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Determine tag based on git commit
      id: set-tag
      run: |
        if [ "${{ github.base_ref }}" = "main" ]; then
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
        elif [ "${{ github.base_ref }}" = "develop" ]; then
          echo "::set-output name=tag::dev"
        fi
    - name: Check if tag is defined
      run: exit 1
      if: steps.set-tag.outputs.tag == ''
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.set-tag.outputs.tag }}
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.set-tag.outputs.tag }}
